module.exports = Object.freeze({
  id: null,
  order_id: 0,
  grade: null,
  pathway: null,
  challenge: null,
  session: null,
  classification: null,
  status: App.config.DEFAULTS.requisition_status,
  production: App.config.DEFAULTS.requisition_production,
  related_to: '',
  resource_id: 0,
  resource_title: '',
  resource_type_group_id: 0,
  resource_type_id: 0,
  resource_version_id: 0,
  requisition_type_str: App.config.DEFAULTS.requisition_type_str,
  location_key: null,
  requested_by_str: App.user.fullName,
  created_at: null,
  updated_at: null,
  due_date: null,
  quicktags: [],
  comments: [],
  versions: [],
  requisition_properties: [],
  user_capabilities: assign({}, require('./user-caps')),
  minimum_age: 3,
  maximum_age: 15,
  visible_for_student: 1,
  visible_for_parent: 1,
  visible_for_coach: 1,
})
